#!/usr/bin/env bash
#
# convert.sh — Export Claude Code agent definitions to alternative runtimes.
#
# Multi-runtime compatibility: the same agents should work from Claude Code,
# OpenAI Codex, and Cursor. Instead of maintaining three copies by hand, the
# source of truth lives in `agents/` (package directory). This script reads
# agent definitions and generates thin projections into:
#
#   .agents/     — universal plain markdown (Cursor-compatible rule files)
#   .codex/      — Codex layout with agents/ and settings.yaml
#
# Inspired by the much larger `convert.sh` from msitarzewski/agency-agents
# (supports 9 runtimes). We only need 2 for the MVP — trimmed to ~100 lines.
#
# Usage:
#   scripts/convert.sh            # convert all agents to both targets
#   scripts/convert.sh --target agents
#   scripts/convert.sh --target codex
#   scripts/convert.sh --clean    # remove generated directories first
#
# Safe to re-run; output dirs are fully regenerated.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# Primary source: agents/ package directory (source of truth).
# Fallback: .claude/agents/ (built by build-local.sh or the installer).
if [ -d "$PROJECT_DIR/agents" ]; then
  SOURCE_MODE="packages"
  AGENTS_PKG_DIR="$PROJECT_DIR/agents"
else
  SOURCE_MODE="flat"
  SOURCE_DIR="$PROJECT_DIR/.claude/agents"
fi

AGENTS_OUT="$PROJECT_DIR/.agents"
CODEX_OUT="$PROJECT_DIR/.codex"

TARGET="all"
CLEAN=0

while [ $# -gt 0 ]; do
  case "$1" in
    --target) TARGET="$2"; shift 2 ;;
    --clean)  CLEAN=1; shift ;;
    -h|--help)
      sed -n '2,22p' "$0"
      exit 0
      ;;
    *) echo "Unknown argument: $1" >&2; exit 2 ;;
  esac
done

if [ "$SOURCE_MODE" = "flat" ] && [ ! -d "$SOURCE_DIR" ]; then
  echo "Error: no agents found. Either agents/ (package dir) or .claude/agents/ (built) must exist." >&2
  echo "  Hint: run 'bin/build-local.sh' to generate .claude/agents/ from agents/." >&2
  exit 1
fi

log() { printf '• %s\n' "$*"; }

# Iterate over agent source files. Yields: name src_path
# In packages mode: agents/{name}/agent.md
# In flat mode: .claude/agents/{name}.md
iter_agents() {
  if [ "$SOURCE_MODE" = "packages" ]; then
    for agent_dir in "$AGENTS_PKG_DIR"/*/; do
      local name
      name=$(basename "$agent_dir")
      [ "${name:0:1}" = "_" ] && continue
      [ ! -f "$agent_dir/agent.md" ] && continue
      echo "$name" "$agent_dir/agent.md"
    done
  else
    for src in "$SOURCE_DIR"/*.md; do
      [ -f "$src" ] || continue
      local name
      name=$(basename "$src")
      echo "${name%.md}" "$src"
    done
  fi
}

# Strip the Claude Code frontmatter (tools/model/skills) — other runtimes
# either ignore it or use a different schema. Keep name/description.
strip_claude_frontmatter() {
  local src="$1"
  awk '
    BEGIN { in_fm = 0; fm_seen = 0 }
    /^---$/ {
      if (!fm_seen) { in_fm = 1; fm_seen = 1; print; next }
      else if (in_fm) { in_fm = 0; print; next }
    }
    in_fm {
      # keep only name and description inside frontmatter
      if ($0 ~ /^name:/ || $0 ~ /^description:/) print
      next
    }
    { print }
  ' "$src"
}

convert_to_agents() {
  log "Generating $AGENTS_OUT/"
  [ $CLEAN -eq 1 ] && rm -rf "$AGENTS_OUT"
  mkdir -p "$AGENTS_OUT"
  while read -r name src; do
    strip_claude_frontmatter "$src" > "$AGENTS_OUT/$name.md"
  done < <(iter_agents)
  cat > "$AGENTS_OUT/README.md" <<'MD'
# .agents/

Auto-generated from `agents/` by `scripts/convert.sh`.
Do not edit files here — edit the source in `agents/` and re-run the script.

This directory is a universal plain-markdown projection of the project's agents.
Cursor and other runtimes that consume markdown rules can point here.
MD
}

convert_to_codex() {
  log "Generating $CODEX_OUT/"
  [ $CLEAN -eq 1 ] && rm -rf "$CODEX_OUT"
  mkdir -p "$CODEX_OUT/agents"
  while read -r name src; do
    strip_claude_frontmatter "$src" > "$CODEX_OUT/agents/$name.md"
  done < <(iter_agents)
  cat > "$CODEX_OUT/settings.yaml" <<'YAML'
# Codex runtime settings for the project's agents.
# Auto-generated by scripts/convert.sh from .claude/settings.json.
# Only a minimal subset is mapped; runtime-specific hooks are not ported.
agents_dir: agents/
project:
  name: project
  description: (edit in .codex/settings.yaml after install)
YAML
  cat > "$CODEX_OUT/README.md" <<'MD'
# .codex/

Auto-generated from `agents/` by `scripts/convert.sh`.
Do not edit files here — edit the source in `agents/` and re-run the script.

Codex layout:
- `agents/*.md` — agent definitions (frontmatter stripped to name + description)
- `settings.yaml` — minimal Codex runtime configuration
MD
}

case "$TARGET" in
  all)    convert_to_agents; convert_to_codex ;;
  agents) convert_to_agents ;;
  codex)  convert_to_codex ;;
  *) echo "Unknown --target: $TARGET (valid: all, agents, codex)" >&2; exit 2 ;;
esac

log "Done."
