#!/usr/bin/env bash
#
# convert.sh — Export Claude Code agent definitions to alternative runtimes.
#
# PLAN.md specifies multi-runtime compatibility: the same agents should work
# from Claude Code, OpenAI Codex, and Cursor. Instead of maintaining three
# copies by hand, the source of truth lives in `.claude/agents/*.md` and this
# script generates thin projections into:
#
#   .agents/     — universal plain markdown (Cursor-compatible rule files)
#   .codex/      — Codex layout with agents/ and settings.yaml
#
# Inspired by the much larger `convert.sh` from msitarzewski/agency-agents
# (supports 9 runtimes). We only need 2 for the MVP — trimmed to ~100 lines.
#
# Usage:
#   scripts/convert.sh            # convert all agents to both targets
#   scripts/convert.sh --target agents
#   scripts/convert.sh --target codex
#   scripts/convert.sh --clean    # remove generated directories first
#
# Safe to re-run; output dirs are fully regenerated.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
SOURCE_DIR="$PROJECT_DIR/.claude/agents"

AGENTS_OUT="$PROJECT_DIR/.agents"
CODEX_OUT="$PROJECT_DIR/.codex"

TARGET="all"
CLEAN=0

while [ $# -gt 0 ]; do
  case "$1" in
    --target) TARGET="$2"; shift 2 ;;
    --clean)  CLEAN=1; shift ;;
    -h|--help)
      sed -n '2,22p' "$0"
      exit 0
      ;;
    *) echo "Unknown argument: $1" >&2; exit 2 ;;
  esac
done

if [ ! -d "$SOURCE_DIR" ]; then
  echo "Error: source agents dir not found: $SOURCE_DIR" >&2
  exit 1
fi

log() { printf '• %s\n' "$*"; }

# Strip the Claude Code frontmatter (tools/model/skills) — other runtimes
# either ignore it or use a different schema. Keep name/description.
strip_claude_frontmatter() {
  local src="$1"
  awk '
    BEGIN { in_fm = 0; fm_seen = 0 }
    /^---$/ {
      if (!fm_seen) { in_fm = 1; fm_seen = 1; print; next }
      else if (in_fm) { in_fm = 0; print; next }
    }
    in_fm {
      # keep only name and description inside frontmatter
      if ($0 ~ /^name:/ || $0 ~ /^description:/) print
      next
    }
    { print }
  ' "$src"
}

convert_to_agents() {
  log "Generating $AGENTS_OUT/"
  [ $CLEAN -eq 1 ] && rm -rf "$AGENTS_OUT"
  mkdir -p "$AGENTS_OUT"
  for src in "$SOURCE_DIR"/*.md; do
    [ -f "$src" ] || continue
    local name
    name=$(basename "$src")
    strip_claude_frontmatter "$src" > "$AGENTS_OUT/$name"
  done
  cat > "$AGENTS_OUT/README.md" <<'MD'
# .agents/

Auto-generated from `.claude/agents/` by `scripts/convert.sh`.
Do not edit files here — edit the source in `.claude/agents/` and re-run the script.

This directory is a universal plain-markdown projection of the project's agents.
Cursor and other runtimes that consume markdown rules can point here.
MD
}

convert_to_codex() {
  log "Generating $CODEX_OUT/"
  [ $CLEAN -eq 1 ] && rm -rf "$CODEX_OUT"
  mkdir -p "$CODEX_OUT/agents"
  for src in "$SOURCE_DIR"/*.md; do
    [ -f "$src" ] || continue
    local name
    name=$(basename "$src")
    strip_claude_frontmatter "$src" > "$CODEX_OUT/agents/$name"
  done
  cat > "$CODEX_OUT/settings.yaml" <<'YAML'
# Codex runtime settings for the project's agents.
# Auto-generated by scripts/convert.sh from .claude/settings.json.
# Only a minimal subset is mapped; runtime-specific hooks are not ported.
agents_dir: agents/
project:
  name: project
  description: (edit in .codex/settings.yaml after install)
YAML
  cat > "$CODEX_OUT/README.md" <<'MD'
# .codex/

Auto-generated from `.claude/agents/` by `scripts/convert.sh`.
Do not edit files here — edit the source in `.claude/agents/` and re-run the script.

Codex layout:
- `agents/*.md` — agent definitions (frontmatter stripped to name + description)
- `settings.yaml` — minimal Codex runtime configuration
MD
}

case "$TARGET" in
  all)    convert_to_agents; convert_to_codex ;;
  agents) convert_to_agents ;;
  codex)  convert_to_codex ;;
  *) echo "Unknown --target: $TARGET (valid: all, agents, codex)" >&2; exit 2 ;;
esac

log "Done."
